name: Backup XML File to GitHub

on:
  schedule:
  - cron: "0 */3 * * *" # Runs every 3 hours
  workflow_dispatch:
    # Allows manual trigger

jobs:
  backup-xml:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Kubernetes (kubectl)
      uses: azure/setup-kubectl@v3
      with:
        version: v1.29.0 # Adjust based on your cluster version

    - name: Configure AKS Credentials
      run: |
        az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
        az aks get-credentials --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AZURE_AKS_CLUSTER }}

    - name: Find Nginx Pod Name
      run: echo "POD_NAME=$(kubectl get pods -l app=nginx -o jsonpath='{.items[0].metadata.name}')" >> $GITHUB_ENV

    - name: Copy XML File from Pod
      run: kubectl cp $POD_NAME:/usr/share/nginx/html/config.xml ./backup/config.xml

    - name: Commit and Push Backup
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add backup/config.xml
        git commit -m "Backup XML file - $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
