apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-api
  template:
    metadata:
      labels:
        app: python-api
    spec:
      containers:
        - name: python-api
          image: my-python-api:latest
          volumeMounts:
            - mountPath: "/mnt/blob/xml"
              name: xml-storage
      volumes:
        - name: xml-storage
          persistentVolumeClaim:
            claimName: blobfuse-pvc-xml
