apiVersion: v1
kind: PersistentVolume
metadata:
  name: blobfuse-pv-xml
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: blob.csi.azure.com
    volumeHandle: <STORAGE_ACCOUNT>#xml
    volumeAttributes:
      containerName: xml
    nodePublishSecretRef:
      name: blobfuse-secret
