apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-web
  template:
    metadata:
      labels:
        app: nginx-web
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        volumeMounts:
        - name: web-files
          mountPath: /usr/share/nginx/html
      volumes:
      - name: web-files
        persistentVolumeClaim:
          claimName: azurefile-pvc
